/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistrictIntelligenceRouteImport } from './routes/district-intelligence'
import { Route as ModelEvaluationRouteImport } from './routes/model-evaluation'
import { Route as MpIntelligenceRouteImport } from './routes/mp-intelligence'
import { Route as NationalIntelligenceRouteImport } from './routes/national-intelligence'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ProjectInvestigationRouteImport } from './routes/project-investigation'
import { Route as RiskMapRouteImport } from './routes/risk-map'
import { Route as RiskQueueRouteImport } from './routes/risk-queue'
import { Route as StateIntelligenceRouteImport } from './routes/state-intelligence'
import { Route as WorksRouteImport } from './routes/works'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictIntelligenceRoute = DistrictIntelligenceRouteImport.update({
  id: '/district-intelligence',
  path: '/district-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelEvaluationRoute = ModelEvaluationRouteImport.update({
  id: '/model-evaluation',
  path: '/model-evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const MpIntelligenceRoute = MpIntelligenceRouteImport.update({
  id: '/mp-intelligence',
  path: '/mp-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalIntelligenceRoute = NationalIntelligenceRouteImport.update({
  id: '/national-intelligence',
  path: '/national-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectInvestigationRoute = ProjectInvestigationRouteImport.update({
  id: '/project-investigation',
  path: '/project-investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskMapRoute = RiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskQueueRoute = RiskQueueRouteImport.update({
  id: '/risk-queue',
  path: '/risk-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const StateIntelligenceRoute = StateIntelligenceRouteImport.update({
  id: '/state-intelligence',
  path: '/state-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/district-intelligence': typeof DistrictIntelligenceRoute
  '/model-evaluation': typeof ModelEvaluationRoute
  '/mp-intelligence': typeof MpIntelligenceRoute
  '/national-intelligence': typeof NationalIntelligenceRoute
  '/payments': typeof PaymentsRoute
  '/project-investigation': typeof ProjectInvestigationRoute
  '/risk-map': typeof RiskMapRoute
  '/risk-queue': typeof RiskQueueRoute
  '/state-intelligence': typeof StateIntelligenceRoute
  '/works': typeof WorksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/district-intelligence': typeof DistrictIntelligenceRoute
  '/model-evaluation': typeof ModelEvaluationRoute
  '/mp-intelligence': typeof MpIntelligenceRoute
  '/national-intelligence': typeof NationalIntelligenceRoute
  '/payments': typeof PaymentsRoute
  '/project-investigation': typeof ProjectInvestigationRoute
  '/risk-map': typeof RiskMapRoute
  '/risk-queue': typeof RiskQueueRoute
  '/state-intelligence': typeof StateIntelligenceRoute
  '/works': typeof WorksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/district-intelligence': typeof DistrictIntelligenceRoute
  '/model-evaluation': typeof ModelEvaluationRoute
  '/mp-intelligence': typeof MpIntelligenceRoute
  '/national-intelligence': typeof NationalIntelligenceRoute
  '/payments': typeof PaymentsRoute
  '/project-investigation': typeof ProjectInvestigationRoute
  '/risk-map': typeof RiskMapRoute
  '/risk-queue': typeof RiskQueueRoute
  '/state-intelligence': typeof StateIntelligenceRoute
  '/works': typeof WorksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/district-intelligence'
    | '/model-evaluation'
    | '/mp-intelligence'
    | '/national-intelligence'
    | '/payments'
    | '/project-investigation'
    | '/risk-map'
    | '/risk-queue'
    | '/state-intelligence'
    | '/works'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/district-intelligence'
    | '/model-evaluation'
    | '/mp-intelligence'
    | '/national-intelligence'
    | '/payments'
    | '/project-investigation'
    | '/risk-map'
    | '/risk-queue'
    | '/state-intelligence'
    | '/works'
  id:
    | '__root__'
    | '/'
    | '/district-intelligence'
    | '/model-evaluation'
    | '/mp-intelligence'
    | '/national-intelligence'
    | '/payments'
    | '/project-investigation'
    | '/risk-map'
    | '/risk-queue'
    | '/state-intelligence'
    | '/works'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistrictIntelligenceRoute: typeof DistrictIntelligenceRoute
  ModelEvaluationRoute: typeof ModelEvaluationRoute
  MpIntelligenceRoute: typeof MpIntelligenceRoute
  NationalIntelligenceRoute: typeof NationalIntelligenceRoute
  PaymentsRoute: typeof PaymentsRoute
  ProjectInvestigationRoute: typeof ProjectInvestigationRoute
  RiskMapRoute: typeof RiskMapRoute
  RiskQueueRoute: typeof RiskQueueRoute
  StateIntelligenceRoute: typeof StateIntelligenceRoute
  WorksRoute: typeof WorksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district-intelligence': {
      id: '/district-intelligence'
      path: '/district-intelligence'
      fullPath: '/district-intelligence'
      preLoaderRoute: typeof DistrictIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-evaluation': {
      id: '/model-evaluation'
      path: '/model-evaluation'
      fullPath: '/model-evaluation'
      preLoaderRoute: typeof ModelEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mp-intelligence': {
      id: '/mp-intelligence'
      path: '/mp-intelligence'
      fullPath: '/mp-intelligence'
      preLoaderRoute: typeof MpIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national-intelligence': {
      id: '/national-intelligence'
      path: '/national-intelligence'
      fullPath: '/national-intelligence'
      preLoaderRoute: typeof NationalIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-investigation': {
      id: '/project-investigation'
      path: '/project-investigation'
      fullPath: '/project-investigation'
      preLoaderRoute: typeof ProjectInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-map': {
      id: '/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof RiskMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-queue': {
      id: '/risk-queue'
      path: '/risk-queue'
      fullPath: '/risk-queue'
      preLoaderRoute: typeof RiskQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/state-intelligence': {
      id: '/state-intelligence'
      path: '/state-intelligence'
      fullPath: '/state-intelligence'
      preLoaderRoute: typeof StateIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistrictIntelligenceRoute: DistrictIntelligenceRoute,
  ModelEvaluationRoute: ModelEvaluationRoute,
  MpIntelligenceRoute: MpIntelligenceRoute,
  NationalIntelligenceRoute: NationalIntelligenceRoute,
  PaymentsRoute: PaymentsRoute,
  ProjectInvestigationRoute: ProjectInvestigationRoute,
  RiskMapRoute: RiskMapRoute,
  RiskQueueRoute: RiskQueueRoute,
  StateIntelligenceRoute: StateIntelligenceRoute,
  WorksRoute: WorksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
