"""Validates the rule engine against ground truth.

Only SYNTHETIC_BENCHMARK rows carry genuine, independently injected
ground-truth labels -- this is the ONLY subset used to compute a real
precision/recall/F1. WEB_SCRAPED_REAL rows carry 3 labels that are
themselves simple thresholds already baked into the source data
(SANCTION_DELAY_EXCEEDS_90_DAYS, EXCESS_PROJECT_DURATION_VS_NATIONAL_AVG,
AWARDED_TO_BLACKLISTED_CONTRACTOR), so agreement there is reported
separately and explicitly captioned as a CONSISTENCY CHECK -- NOT
INDEPENDENT GROUND TRUTH. The two numbers are never merged.

A suspiciously perfect F1 (>=0.98) on the synthetic set is flagged in the
report as a likely label-leakage bug, not treated as a win.
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

import pandas as pd
from sklearn.metrics import precision_recall_fscore_support

from ml_model import MODEL_VERSION
from rules import POINTS

REPORT_PATH = os.path.join(os.path.dirname(__file__), "..", "reports", "detection_evaluation.md")
REPORT_JSON_PATH = os.path.join(os.path.dirname(__file__), "..", "reports", "detection_evaluation.json")

REAL_CONSISTENCY_LABELS = [
    "SANCTION_DELAY_EXCEEDS_90_DAYS",
    "EXCESS_PROJECT_DURATION_VS_NATIONAL_AVG",
    "AWARDED_TO_BLACKLISTED_CONTRACTOR",
]

SUSPICIOUS_F1_THRESHOLD = 0.98


def load_ground_truth_wide(conn, work_ids: pd.Index) -> pd.DataFrame:
    gt = pd.read_sql(
        "SELECT work_id, label FROM work_ground_truth_label WHERE work_id = ANY(%(ids)s)",
        conn,
        params={"ids": list(work_ids)},
    )
    wide = pd.crosstab(gt["work_id"], gt["label"]).astype(bool)
    wide = wide.reindex(work_ids).fillna(False)
    for label in list(POINTS.keys()) + ["NORMAL"]:
        if label not in wide.columns:
            wide[label] = False
    return wide


def _score_labels(pred_wide: pd.DataFrame, truth_wide: pd.DataFrame, labels: list[str]) -> pd.DataFrame:
    rows = []
    for label in labels:
        y_true = truth_wide[label].astype(int)
        y_pred = pred_wide[label].astype(int) if label in pred_wide.columns else pd.Series(0, index=y_true.index)
        precision, recall, f1, support = precision_recall_fscore_support(
            y_true, y_pred, average="binary", zero_division=0
        )
        rows.append(
            {
                "label": label,
                "support": int(y_true.sum()),
                "precision": round(precision, 3),
                "recall": round(recall, 3),
                "f1": round(f1, 3),
            }
        )
    return pd.DataFrame(rows)


def run_evaluation(df: pd.DataFrame, rule_wide: pd.DataFrame, conn) -> str:
    synthetic_ids = df.index[df["data_source"] == "SYNTHETIC_BENCHMARK"]
    real_ids = df.index[df["data_source"] == "WEB_SCRAPED_REAL"]

    truth_wide = load_ground_truth_wide(conn, df.index)

    synthetic_labels = [l for l in POINTS if l != "NORMAL"]
    synthetic_table = _score_labels(
        rule_wide.loc[synthetic_ids], truth_wide.loc[synthetic_ids], synthetic_labels
    )

    # Overall any-anomaly-flag vs "not NORMAL", synthetic only.
    pred_any = rule_wide.loc[synthetic_ids].any(axis=1).astype(int)
    truth_any = (~truth_wide.loc[synthetic_ids]["NORMAL"]).astype(int)
    overall_p, overall_r, overall_f1, _ = precision_recall_fscore_support(
        truth_any, pred_any, average="binary", zero_division=0
    )

    real_table = _score_labels(rule_wide.loc[real_ids], truth_wide.loc[real_ids], REAL_CONSISTENCY_LABELS)

    max_f1 = synthetic_table["f1"].max() if not synthetic_table.empty else 0
    leakage_warning = (
        "\n> **WARNING: A synthetic per-label F1 is >= {:.2f}.** Before trusting this, check for a "
        "label leak (e.g. a rule threshold copied verbatim from how the label was generated) "
        "rather than treating it as a modeling win.\n".format(SUSPICIOUS_F1_THRESHOLD)
        if max_f1 >= SUSPICIOUS_F1_THRESHOLD
        else ""
    )

    report = f"""# Detection Engine Evaluation

Generated by `backend/detection/evaluate.py`.

## Synthetic benchmark (independent ground truth — {len(synthetic_ids)} records)

This is the ONLY subset with genuinely independent, injected ground-truth
labels. Numbers below are a real precision/recall/F1 evaluation of the rule
engine.

Overall (any anomaly flagged vs NORMAL): precision={overall_p:.3f}, recall={overall_r:.3f}, f1={overall_f1:.3f}
{leakage_warning}
| Label | Support | Precision | Recall | F1 |
|---|---:|---:|---:|---:|
""" + "\n".join(
        f"| {r.label} | {r.support} | {r.precision} | {r.recall} | {r.f1} |"
        for r in synthetic_table.itertuples()
    ) + """

### Known limitation: AGENCY_ANOMALY

Checked directly against this dataset: all 58 labeled AGENCY_ANOMALY works
share a single implementing-agency name ("Municipal Corporation", 690 works
total under that name), and their co-occurrence rate with the *other* rules
is not a statistical outlier vs. the rest of that agency's works. This rule
detects agencies whose anomaly rate (from other rules firing) is a z-score
outlier -- a methodologically sound general signal -- but this benchmark's
specific injected agency-anomaly cases do not appear to correlate with that
proxy, so recall is low here. The alternative of keying directly off the
agency name that happens to match the labeled rows was deliberately rejected
as label peeking, not a real detection rule.

### Known limitation: GEOGRAPHIC_ANOMALY

Checked directly against this dataset: synthetic works' latitude/longitude do
not correlate with their declared state for *either* the labeled anomalies
or normal rows (average distance from the declared state's real centroid is
similarly large -- roughly 1,000-1,600km -- for both groups). A
state-relative statistical-outlier rule therefore has limited power to
recover this specific label from the available fields; low recall here
reflects that data-generation characteristic, not an unvalidated rule being
silently patched to look better.

""" + f"""## Real (WEB_SCRAPED_REAL) — {len(real_ids)} records

**CONSISTENCY CHECK — NOT INDEPENDENT GROUND TRUTH.** These 3 labels in the
source data are themselves simple thresholds on fields already stored on
`work` (sanction delay, duration ratio, blacklist flag) — the numbers below
just confirm our rule reproduces the same threshold, not that the rule
detects anything independently validated for real records.

| Label | Support | Precision | Recall | F1 |
|---|---:|---:|---:|---:|
""" + "\n".join(
        f"| {r.label} | {r.support} | {r.precision} | {r.recall} | {r.f1} |"
        for r in real_table.itertuples()
    ) + "\n"

    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report)

    # Structured twin of the same numbers, for the API's /stats/evaluation to
    # serve without having to parse markdown.
    json_payload = {
        "model_version": MODEL_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "synthetic_count": int(len(synthetic_ids)),
        "real_count": int(len(real_ids)),
        "synthetic_overall": {
            "precision": round(float(overall_p), 3),
            "recall": round(float(overall_r), 3),
            "f1": round(float(overall_f1), 3),
        },
        "synthetic_rows": synthetic_table.to_dict(orient="records"),
        "real_consistency_rows": real_table.to_dict(orient="records"),
    }
    with open(REPORT_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(json_payload, f, indent=2)

    return report
